from ui.styles.base_style import BaseStyles, scale


# ---- exclusive for add page ----
class AddStyles:
    # header
    HEADER_TITLE_LABEL_W = scale(1630)
    HEADER_TITLE_LABEL_FG_COLOR = BaseStyles.TRANSPARENT
    HEADER_TITLE_TEXT_COLOR = BaseStyles.BLACK


    # transaction form
    FORM_TOP_SECTION_FG_COLOR = BaseStyles.WHITE
    
    DATE_MENU_H = scale(60)
    YEAR_MENU_W = scale(450)
    MONTH_MENU_W = scale(500) 
    DAY_MENU_W = scale(450)
    DATE_LABEL_TEXT_COLOR = BaseStyles.BLACK
    DATE_LABEL_FG_COLOR = BaseStyles.TRANSPARENT
    DATE_MENU_TEXT_COLOR = BaseStyles.BLACK
    DATE_MENU_FG_COLOR = BaseStyles.GREY
    DATE_MENU_HOVER_COLOR = BaseStyles.GREY
    DATE_MENU_FRAME_FG_COLOR = BaseStyles.TRANSPARENT
    DATE_DROPDOWN_FG_COLOR = BaseStyles.WHITE
    DATE_DROPDOWN_HOVER_COLOR = BaseStyles.GREY
    DATE_DROPDOWN_TEXT_COLOR = BaseStyles.BLACK
    DATE_BTN_FG_COLOR = BaseStyles.GREY
    DATE_BTN_HOVER_COLOR = BaseStyles.DARK_YELLOW

    FORM_MID_SECTION_FG_COLOR = BaseStyles.WHITE

    CATEGORY_MENU_W = scale(800)
    CATEGORY_MENU_H = scale(60)
    CATEGORY_LABEL_TEXT_COLOR = BaseStyles.BLACK
    CATEGORY_LABEL_FG_COLOR = BaseStyles.TRANSPARENT
    CATEGORY_MENU_TEXT_COLOR = BaseStyles.BLACK
    CATEGORY_MENU_FG_COLOR = BaseStyles.GREY
    CATEGORY_MENU_HOVER_COLOR = BaseStyles.DARK_BLUE
    CATEGORY_DROPDOWN_TEXT_COLOR = BaseStyles.BLACK
    CATEGORY_DROPDOWN_FG_COLOR = BaseStyles.WHITE
    CATEGORY_DROPDOWN_HOVER_COLOR = BaseStyles.GREY
    CATEGORY_BTN_FG_COLOR = BaseStyles.GREY
    CATEGORY_BTN_HOVER_COLOR = BaseStyles.DARK_YELLOW

    DESCRIPTION_ENTRY_W = scale(600)
    DESCRIPTION_ENTRY_H = scale(60)
    DESCRIPTION_LABEL_TEXT_COLOR = BaseStyles.BLACK
    DESCRIPTION_LABEL_FG_COLOR = BaseStyles.TRANSPARENT
    DESCRIPTION_ENTRY_TEXT_COLOR = BaseStyles.BLACK
    DESCRIPTION_ENTRY_FG_COLOR = BaseStyles.GREY
    DESCRIPTION_ENTRY_BG_COLOR = BaseStyles.TRANSPARENT
    DESCRIPTION_PLACEHOLDER_TEXT_COLOR = BaseStyles.DARK_GREY
    
    FORM_BOT_SECTION_FG_COLOR = BaseStyles.WHITE

    AMOUNT_ENTRY_W = scale(1430)
    AMOUNT_ENTRY_H = scale(60)
    AMOUNT_LABEL_TEXT_COLOR = BaseStyles.BLACK
    AMOUNT_LABEL_FG_COLOR = BaseStyles.TRANSPARENT
    AMOUNT_ENTRY_TEXT_COLOR = BaseStyles.BLACK
    AMOUNT_ENTRY_FG_COLOR = BaseStyles.GREY
    AMOUNT_ENTRY_BG_COLOR = BaseStyles.TRANSPARENT
    AMOUNT_PLACEHOLDER_TEXT_COLOR = BaseStyles.DARK_GREY
    

    # page tabs
    TAB_W = scale(350)
    TAB_H = scale(60)

    OFF_TAB_BTN_FG_COLOR = BaseStyles.WHITE
    OFF_TAB_BTN_HOVER_COLOR = BaseStyles.LIGHT_GREY
    OFF_TAB_TEXT_COLOR = BaseStyles.BLACK

    ON_TAB_BTN_FG_COLOR = BaseStyles.DARKEST_BLUE
    ON_TAB_BTN_HOVER_COLOR = BaseStyles.DARK_BLUE
    ON_TAB_TEXT_COLOR = BaseStyles.WHITE


    # main page
    MAIN_FRAME_FG_COLOR = BaseStyles.TRANSPARENT

    HEADER_SECTION_FG_COLOR = BaseStyles.TRANSPARENT

    FORMS_SECTION_FG_COLOR = BaseStyles.TRANSPARENT
    FORM_FRAME_FG_COLOR = BaseStyles.WHITE

    TABS_FRAME_FG_COLOR = BaseStyles.TRANSPARENT