from .base import BaseStyles
from .login import LoginStyles
from .app import AppStyles
from .sidebar import SidebarStyles
from .profile import ProfileStyles
from .home import HomeStyles
from .edit import EditStyles
from .history import HistoryStyles
from .add import AddStyles
from .popup_win import PopUpWinStyles