from .base import BaseStyles
from .app import AppStyles
from .sidebar import SidebarStyles
from .profile import ProfileStyles
from .home import HomeStyles
from .edit import EditStyles
from .history import HistoryStyles
from .add import AddStyles
from .save_btn import SaveStyles
from .popup_win import PopUpWinStyles